/* Build-time: @svg-maps/uzbekistan (CC BY 4.0, Victor Cazanave) → ixcham data fayl */
import fs from 'node:fs';
import map from '@svg-maps/uzbekistan';
const round = d => d.replace(/-?\d+\.\d+/g, n => (Math.round(parseFloat(n) * 10) / 10).toString());
const NAMES = { andijan: 'Andijon', bukhara: 'Buxoro', fergana: 'Farg’ona', jizzakh: 'Jizzax', namangan: 'Namangan', navoiy: 'Navoiy', qashqadaryo: 'Qashqadaryo',
  karakalpakstan: 'Qoraqalpog’iston', samarqand: 'Samarqand', sirdaryo: 'Sirdaryo', surxondaryo: 'Surxondaryo', xorazm: 'Xorazm', 'aral-sea': 'Orol dengizi' };
let tk = 0;
const regions = map.locations.map(l => {
  let id = l.id, name = NAMES[id];
  if (id === 'tashkent') { id = l.path.length < 1500 ? 'tashkent-city' : 'tashkent-region'; name = id === 'tashkent-city' ? 'Toshkent shahri' : 'Toshkent viloyati'; tk++; }
  return { id, name, d: round(l.path) };
});
const out = `/* generated by gen-map.mjs — Uzbekistan map: @svg-maps/uzbekistan (CC BY 4.0) */\nwindow.muUzMap = ${JSON.stringify({ viewBox: map.viewBox, regions })};\n`;
fs.writeFileSync(new URL('./a-map.js', import.meta.url), out);
console.log('a-map.js', (out.length / 1024).toFixed(1) + ' KB', regions.map(r => r.id).join(','));
