/* ==========================================================================
   10-hero — WebGL dotted Earth (world-atlas land dots, generated by gen-land.mjs),
   route arcs from Toshkent with travelling pulses, atmosphere, astrolabe ring,
   orbiting satellite, 3.6k-star sky, UnrealBloom (desktop).
   Overlay: scramble eyebrow, char-flip H1 + rotating slot word that drives the
   highlighted transport mode on the globe, live shipment card, count-up stats.
   ========================================================================== */
const HERO_DEG = Math.PI / 180;
const HERO_TASH = { n: 'Toshkent', lat: 41.31, lon: 69.24 };
/* m: 0 avto · 1 temir yoʻl · 2 dengiz · 3 avia   rev: pulse travels towards Toshkent */
const HERO_HUBS = [
  { n: 'Shanghai', lat: 31.23, lon: 121.47, m: 1, rev: 1 },
  { n: 'Moskva', lat: 55.76, lon: 37.62, m: 0 },
  { n: 'Istanbul', lat: 41.01, lon: 28.98, m: 0 },
  { n: 'Dubay', lat: 25.2, lon: 55.27, m: 3 },
  { n: 'Berlin', lat: 52.52, lon: 13.4, m: 1 },
  { n: 'Pekin', lat: 39.9, lon: 116.4, m: 1, rev: 1 },
  { n: 'Mumbay', lat: 19.08, lon: 72.88, m: 2, rev: 1 },
  { n: 'London', lat: 51.51, lon: -0.13, m: 3 },
  { n: 'Olmaota', lat: 43.24, lon: 76.89, m: 0, rev: 1 },
  { n: 'Tehron', lat: 35.69, lon: 51.39, m: 0 },
  { n: 'Rotterdam', lat: 51.92, lon: 4.48, m: 2 },
  { n: 'Boku', lat: 40.41, lon: 49.87, m: 2 }
];
const HERO_MODE_HEX = ['#ffc861', '#2ee6d6', '#3d8bff', '#ff5a36'];
const HERO_MODE_VAR = ['var(--gold)', 'var(--turq)', 'var(--azure)', 'var(--coral)'];
const HERO_BASE_SPIN = -64 * HERO_DEG;   /* longitude 64°E faces the camera: Central Asia front and centre */
const HERO_BASE_TILT = 0.55;

const heroVec = (lat, lon, r = 1, out = new THREE.Vector3()) => {
  const la = lat * HERO_DEG, lo = lon * HERO_DEG;
  return out.set(Math.cos(la) * Math.sin(lo) * r, Math.sin(la) * r, Math.cos(la) * Math.cos(lo) * r);
};

/* ------------------------------------------------------------------ shaders */
const HERO_GLSL = {
  dotsV: `
    uniform float uTime, uSize, uReveal, uPingT, uD0, uHoverK;
    uniform vec3 uTash, uPing, uHover, uColA, uColB, uGold;
    attribute float aRnd;
    attribute float aUz;
    varying vec3 vCol;
    varying float vA;
    varying float vGlow;
    void main() {
      vec3 n = normalize(position);
      float ang = acos(clamp(dot(n, uTash), -1.0, 1.0));
      float rv = uReveal * 3.35;
      float vis = 1.0 - smoothstep(rv - 0.2, rv, ang);
      float front = exp(-pow((ang - rv) * 7.0, 2.0)) * step(0.001, uReveal) * (1.0 - step(0.999, uReveal));
      float wr = mod(uTime * 0.42, 5.2) - 0.15;
      float wave = exp(-pow((ang - wr) * 6.5, 2.0)) * (1.0 - smoothstep(0.4, 3.2, wr)) * step(0.999, uReveal);
      float pa = acos(clamp(dot(n, uPing), -1.0, 1.0));
      float pr = uPingT * 1.15;
      float ping = exp(-pow((pa - pr) * 8.0, 2.0)) * exp(-uPingT * 0.85) * step(0.0, uPingT);
      float ha = acos(clamp(dot(n, uHover), -1.0, 1.0));
      float hov = exp(-pow(ha / 0.13, 2.0)) * uHoverK;
      float g = wave * 0.8 + ping * 1.7 + front * 1.5 + hov * 1.1;
      vec4 mv = modelViewMatrix * vec4(position * (1.0 + 0.02 * g), 1.0);
      vec3 vn = normalize(normalMatrix * n);
      float facing = clamp(dot(vn, normalize(-mv.xyz)), 0.0, 1.0);
      float tw = 0.7 + 0.3 * sin(uTime * (0.7 + aRnd * 2.1) + aRnd * 60.0);
      float lon = atan(n.x, n.z);
      float t = clamp(0.3 + 0.5 * n.y + 0.22 * sin(lon * 2.0 + n.y * 4.0), 0.0, 1.0);
      vCol = mix(mix(uColA, uColB, t), uGold, aUz);
      vGlow = g + aUz * 0.45;
      vA = vis * smoothstep(0.0, 0.45, facing) * tw;
      gl_PointSize = uSize * (uD0 / -mv.z) * (0.55 + 0.45 * facing) * (1.0 + 0.6 * g + aUz * 0.3);
      gl_Position = projectionMatrix * mv;
    }`,
  dotsF: `
    varying vec3 vCol;
    varying float vA;
    varying float vGlow;
    void main() {
      vec2 c = gl_PointCoord - 0.5;
      float d = length(c);
      if (d > 0.5) discard;
      float a = smoothstep(0.5, 0.16, d);
      float core = smoothstep(0.24, 0.0, d);
      vec3 col = vCol * (0.72 + vGlow * 1.25) + vec3(core * (0.06 + 0.5 * vGlow));
      gl_FragColor = vec4(col * a * vA, 1.0);
      #include <colorspace_fragment>
    }`,
  fresV: `
    varying vec3 vN;
    varying vec3 vV;
    void main() {
      vec4 mv = modelViewMatrix * vec4(position, 1.0);
      vN = normalize(normalMatrix * normal);
      vV = normalize(-mv.xyz);
      gl_Position = projectionMatrix * mv;
    }`,
  oceanF: `
    uniform vec3 uDeep, uRim, uLit;
    uniform float uAtmo;
    varying vec3 vN;
    varying vec3 vV;
    void main() {
      float ndv = max(dot(vN, vV), 0.0);
      float fres = pow(1.0 - ndv, 4.0);
      vec3 L = normalize(vec3(-0.5, 0.62, 0.6));
      float diff = max(dot(vN, L), 0.0);
      vec3 col = uDeep * (0.42 + 0.85 * diff) + uLit * pow(diff, 10.0) * 0.05 + uRim * fres * 0.7 * uAtmo;
      gl_FragColor = vec4(col, 1.0);
      #include <colorspace_fragment>
    }`,
  atmoF: `
    uniform vec3 uColA, uColB;
    uniform float uAtmo, uEdge;
    varying vec3 vN;
    varying vec3 vV;
    void main() {
      float k = clamp(-dot(vN, vV) / uEdge, 0.0, 1.0);
      float i = pow(k, 3.0) * 0.8 + pow(k, 12.0) * 0.5;
      vec2 dir = normalize(vN.xy + 1e-5);
      float side = 0.45 + 0.55 * max(dot(dir, normalize(vec2(-0.6, 0.8))), -0.4);
      vec3 col = mix(uColB, uColA, k) * i * side * 0.6 * uAtmo;
      gl_FragColor = vec4(col, 1.0);
      #include <colorspace_fragment>
    }`,
  starsV: `
    uniform float uTime, uPx, uFade;
    attribute float aSize;
    attribute float aRnd;
    attribute vec3 aCol;
    varying vec3 vCol;
    varying float vA;
    varying float vBig;
    void main() {
      vec4 mv = modelViewMatrix * vec4(position, 1.0);
      float tw = 0.5 + 0.5 * sin(uTime * (0.5 + aRnd * 2.4) + aRnd * 80.0);
      vBig = step(2.5, aSize);
      vA = mix(0.35 + 0.65 * tw, 0.7 + 0.3 * tw, vBig) * uFade;
      vCol = aCol;
      gl_PointSize = aSize * uPx * mix(1.0, 3.4, vBig);
      gl_Position = projectionMatrix * mv;
    }`,
  starsF: `
    varying vec3 vCol;
    varying float vA;
    varying float vBig;
    void main() {
      vec2 c = gl_PointCoord - 0.5;
      float d = length(c);
      float a;
      if (vBig > 0.5) {
        float spikes = max(0.0, 1.0 - abs(c.x) * 34.0) * max(0.0, 1.0 - abs(c.y) * 2.1)
                     + max(0.0, 1.0 - abs(c.y) * 34.0) * max(0.0, 1.0 - abs(c.x) * 2.1);
        a = exp(-d * d * 110.0) + spikes * 0.5 + exp(-d * d * 26.0) * 0.22;
      } else {
        a = smoothstep(0.5, 0.0, d);
      }
      gl_FragColor = vec4(vCol * a * vA, 1.0);
      #include <colorspace_fragment>
    }`,
  uvV: `
    varying vec2 vUv;
    void main() { vUv = uv; gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0); }`,
  arcF: `
    uniform float uTime, uDraw, uHi, uSpeed, uOff, uAlpha, uRev;
    uniform vec3 uCol;
    varying vec2 vUv;
    void main() {
      float p = vUv.x;
      if (p > uDraw) discard;
      float q = mix(p, 1.0 - p, uRev);
      float head = fract(uTime * uSpeed + uOff);
      float d = fract(head - q);
      float tail = exp(-d * 7.5);
      float drawHead = exp(-abs(uDraw - p) * 26.0) * (1.0 - step(0.999, uDraw));
      float ends = smoothstep(0.0, 0.035, p) * smoothstep(1.0, 0.965, p);
      float a = (0.14 + 0.36 * uHi + tail * (0.45 + 1.25 * uHi) + drawHead * 2.2) * ends * uAlpha;
      vec3 col = uCol * a + vec3(pow(tail, 4.0) * (0.25 + 0.6 * uHi) * ends * uAlpha);
      gl_FragColor = vec4(col, 1.0);
      #include <colorspace_fragment>
    }`,
  spriteV: `
    uniform float uPx, uD0;
    attribute vec3 aCol;
    attribute float aA;
    attribute float aSize;
    varying vec3 vCol;
    varying float vA;
    void main() {
      vCol = aCol; vA = aA;
      vec4 mv = modelViewMatrix * vec4(position, 1.0);
      gl_PointSize = aSize * uPx * (uD0 / -mv.z) * (0.5 + 0.5 * aA);
      gl_Position = projectionMatrix * mv;
    }`,
  spriteF: `
    varying vec3 vCol;
    varying float vA;
    void main() {
      vec2 c = gl_PointCoord - 0.5;
      float d2 = dot(c, c);
      float a = exp(-d2 * 60.0) + exp(-d2 * 10.0) * 0.35;
      vec3 col = mix(vCol, vec3(1.0), exp(-d2 * 180.0) * 0.85);
      gl_FragColor = vec4(col * a * vA, 1.0);
      #include <colorspace_fragment>
    }`,
  ringF: `
    uniform float uTime, uOff, uShow, uCount, uSpeed;
    uniform vec3 uCol;
    varying vec2 vUv;
    void main() {
      float r = length(vUv - 0.5) * 2.0;
      float a = 0.0;
      for (int i = 0; i < 3; i++) {
        if (float(i) >= uCount) break;
        float t = fract(uTime * uSpeed + uOff + float(i) / uCount);
        a += smoothstep(0.07, 0.0, abs(r - t)) * (1.0 - t) * (1.0 - t);
      }
      a += smoothstep(0.2, 0.0, abs(r - 0.34)) * 0.0;
      gl_FragColor = vec4(uCol * a * uShow, 1.0);
      #include <colorspace_fragment>
    }`,
  beamF: `
    uniform float uTime, uGrow, uInt;
    uniform vec3 uCol;
    varying vec2 vUv;
    void main() {
      float y = vUv.y;
      if (y > uGrow) discard;
      float a = pow(1.0 - y, 1.7) * (0.7 + 0.3 * sin(y * 38.0 - uTime * 5.0));
      a *= 1.0 - smoothstep(uGrow - 0.18, uGrow, y);
      gl_FragColor = vec4(uCol * a * uInt, 1.0);
      #include <colorspace_fragment>
    }`,
  lineV: `
    attribute float aAng;
    varying float vAng;
    void main() { vAng = aAng; gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0); }`,
  lineF: `
    uniform float uDraw, uHead, uTrail, uAlpha, uEnds;
    uniform vec3 uCol;
    varying float vAng;
    void main() {
      if (vAng > uDraw) discard;
      float d = fract(uHead - vAng);
      float tr = exp(-d * 16.0) * uTrail;
      float ends = mix(1.0, pow(sin(3.14159 * vAng), 0.8), uEnds);
      gl_FragColor = vec4(uCol * (uAlpha + tr) * ends, 1.0);
      #include <colorspace_fragment>
    }`,
  bgV: `
    varying vec2 vUv;
    void main() { vUv = uv; gl_Position = vec4(position.xy, 0.9999, 1.0); }`,
  bgF: `
    uniform float uTime, uAspect, uR, uFade;
    uniform vec2 uC;
    uniform vec3 uBg, uA, uB, uV;
    varying vec2 vUv;
    float hash(vec2 p) { return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453); }
    float noise(vec2 p) {
      vec2 i = floor(p), f = fract(p);
      vec2 u = f * f * (3.0 - 2.0 * f);
      return mix(mix(hash(i), hash(i + vec2(1.0, 0.0)), u.x), mix(hash(i + vec2(0.0, 1.0)), hash(i + vec2(1.0, 1.0)), u.x), u.y);
    }
    float fbm(vec2 p) {
      float v = 0.0, a = 0.5;
      for (int i = 0; i < 4; i++) { v += a * noise(p); p = p * 2.03 + 1.7; a *= 0.5; }
      return v;
    }
    void main() {
      vec2 p = vec2(vUv.x * uAspect, vUv.y);
      vec2 c = vec2(uC.x * uAspect, uC.y);
      float d = length(p - c) / uR;
      vec3 col = uBg;
      col += uB * 0.06 * exp(-max(d - 1.0, 0.0) * 2.2) * smoothstep(0.85, 1.02, d);
      col += uB * 0.025 * exp(-d * 0.9);
      float n = fbm(p * 1.5 + vec2(uTime * 0.01, -uTime * 0.006));
      float n2 = fbm(p * 2.6 - vec2(uTime * 0.007, 0.0) + 7.3);
      col += uV * pow(n, 3.4) * 0.2;
      col += uA * pow(n2, 4.2) * 0.14;
      gl_FragColor = vec4(col * uFade, 1.0);
      #include <colorspace_fragment>
    }`
};

/* ------------------------------------------------------------------ geometry helpers */
function heroLandGeometry(sparse) {
  const L = window.muHeroLand;
  if (!L) return null;
  const land = atob(L.land), uz = atob(L.uz);
  const bit = (s, k) => (s.charCodeAt(k >> 3) >> (k & 7)) & 1;
  const rows = Math.round(180 / L.step);
  const pos = [], rnd = [], uzA = [];
  const v = new THREE.Vector3();
  let k = 0, li = 0;
  for (let i = 0; i < rows; i++) {
    const lat = -90 + (i + 0.5) * L.step;
    const n = Math.max(1, Math.round((360 * Math.cos(lat * Math.PI / 180)) / L.step));
    for (let j = 0; j < n; j++, k++) {
      if (!bit(land, k)) continue;
      const u = bit(uz, li++);
      if (sparse && (i % 2 || j % 2)) continue;
      heroVec(lat, -180 + (j + 0.5) * (360 / n), 1, v);
      pos.push(v.x, v.y, v.z); rnd.push(Math.random()); uzA.push(u);
    }
  }
  const g = new THREE.BufferGeometry();
  g.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3));
  g.setAttribute('aRnd', new THREE.Float32BufferAttribute(rnd, 1));
  g.setAttribute('aUz', new THREE.Float32BufferAttribute(uzA, 1));
  return { geo: g, step: L.step * (sparse ? 2 : 1) };
}

function heroStars(count) {
  const pos = new Float32Array(count * 3), size = new Float32Array(count), rnd = new Float32Array(count), col = new Float32Array(count * 3);
  const tints = [new THREE.Color('#e4ecff'), new THREE.Color('#e4ecff'), new THREE.Color('#bfe9ff'), new THREE.Color('#9ff7ef'), new THREE.Color('#ffe3a8'), new THREE.Color('#c9bcff')];
  const v = new THREE.Vector3();
  for (let i = 0; i < count; i++) {
    v.set(Math.random() * 2 - 1, Math.random() * 2 - 1, Math.random() * 2 - 1);
    if (v.lengthSq() > 1 || v.lengthSq() < 0.01) { i--; continue; }
    v.normalize().multiplyScalar(34 + Math.random() * 46);
    pos.set([v.x, v.y, v.z], i * 3);
    const big = Math.random() < 0.012;
    size[i] = big ? 2.6 + Math.random() * 1.2 : 0.7 + Math.pow(Math.random(), 2.6) * 1.6;
    rnd[i] = Math.random();
    const c = tints[(Math.random() * tints.length) | 0];
    const b = big ? 1 : 0.55 + Math.random() * 0.45;
    col.set([c.r * b, c.g * b, c.b * b], i * 3);
  }
  const g = new THREE.BufferGeometry();
  g.setAttribute('position', new THREE.BufferAttribute(pos, 3));
  g.setAttribute('aSize', new THREE.BufferAttribute(size, 1));
  g.setAttribute('aRnd', new THREE.BufferAttribute(rnd, 1));
  g.setAttribute('aCol', new THREE.BufferAttribute(col, 3));
  return g;
}

/* circle (+ optional tick marks) in the XZ plane with an angle attribute for draw-in / trails */
function heroRingGeometry(r, { ticks = 0, major = 0, tickLen = 0.02, majorLen = 0.05, inner = 0 } = {}) {
  const pos = [], ang = [];
  const seg = 240;
  const P = (a, rr) => [Math.cos(a) * rr, 0, Math.sin(a) * rr];
  const circle = rr => {
    for (let i = 0; i < seg; i++) {
      const a0 = (i / seg) * Math.PI * 2, a1 = ((i + 1) / seg) * Math.PI * 2;
      pos.push(...P(a0, rr), ...P(a1, rr)); ang.push(i / seg, (i + 1) / seg);
    }
  };
  circle(r);
  if (inner) circle(inner);
  if (ticks) {
    for (let i = 0; i < ticks; i++) {
      const a = (i / ticks) * Math.PI * 2;
      const isMajor = major && i % major === 0;
      pos.push(...P(a, r), ...P(a, r + (isMajor ? majorLen : tickLen))); ang.push(i / ticks, i / ticks);
    }
  }
  const g = new THREE.BufferGeometry();
  g.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3));
  g.setAttribute('aAng', new THREE.Float32BufferAttribute(ang, 1));
  return g;
}

/* ================================================================== globe */
function heroGlobe(root, MU) {
  const { gsap } = MU;
  const stage = root.querySelector('.hero-stage');
  const canvas = root.querySelector('.hero-gl');
  const labelsEl = root.querySelector('.hero-labels');
  const stackedMq = window.matchMedia('(max-width: 900px), (orientation: portrait) and (max-width: 1100px)');
  const mobile = MU.isMobile;
  const bloomOn = !mobile;
  const gain = bloomOn ? 1 : 0.62;   /* no bloom = additive in sRGB: tone the glow down */

  const attrs = { alpha: false, antialias: !bloomOn, depth: true, stencil: false, premultipliedAlpha: true, powerPreference: 'high-performance' };
  let ctx = null;
  try { ctx = canvas.getContext('webgl2', attrs); } catch (e) { ctx = null; }
  if (!ctx) { root.classList.add('hero--nogl'); return null; }

  const renderer = new THREE.WebGLRenderer({ canvas, context: ctx, antialias: attrs.antialias, alpha: false });
  const dpr = MU.dpr(1.5);
  renderer.setPixelRatio(dpr);
  renderer.setClearColor(0x03050c, 1);

  const scene = new THREE.Scene();
  const camera = new THREE.PerspectiveCamera(30, 1, 0.1, 200);
  camera.position.set(0, 0, 6);

  const C = hex => new THREE.Color(hex);
  const uTime = { value: 0 };

  /* background nebula (fullscreen) */
  const bgU = {
    uTime, uAspect: { value: 1 }, uR: { value: 0.5 }, uFade: { value: 0 }, uC: { value: new THREE.Vector2(0.7, 0.5) },
    uBg: { value: C('#03050c') }, uA: { value: C('#2ee6d6') }, uB: { value: C('#3d8bff') }, uV: { value: C('#8b6cff') }
  };
  const bg = new THREE.Mesh(new THREE.PlaneGeometry(2, 2), new THREE.ShaderMaterial({
    uniforms: bgU, vertexShader: HERO_GLSL.bgV, fragmentShader: HERO_GLSL.bgF, depthTest: false, depthWrite: false
  }));
  bg.frustumCulled = false; bg.renderOrder = -100;
  scene.add(bg);

  /* stars */
  const starU = { uTime, uPx: { value: dpr }, uFade: { value: 0 } };
  const stars = new THREE.Points(heroStars(mobile ? 1500 : 3600), new THREE.ShaderMaterial({
    uniforms: starU, vertexShader: HERO_GLSL.starsV, fragmentShader: HERO_GLSL.starsF,
    transparent: true, depthWrite: false, blending: THREE.AdditiveBlending
  }));
  stars.frustumCulled = false;
  scene.add(stars);

  /* globe hierarchy: tilt → spin → (geo coords) */
  const tilt = new THREE.Group();
  const spin = new THREE.Group();
  tilt.add(spin); scene.add(tilt);

  const oceanU = { uDeep: { value: C('#0a1433') }, uRim: { value: C('#3d8bff') }, uLit: { value: C('#9ff7ef') }, uAtmo: { value: 0 } };
  const ocean = new THREE.Mesh(new THREE.SphereGeometry(0.994, mobile ? 64 : 96, mobile ? 48 : 72), new THREE.ShaderMaterial({
    uniforms: oceanU, vertexShader: HERO_GLSL.fresV, fragmentShader: HERO_GLSL.oceanF
  }));
  spin.add(ocean);

  const atmoU = { uColA: { value: C('#2ee6d6') }, uColB: { value: C('#3d8bff') }, uAtmo: { value: 0 }, uEdge: { value: 0.5 } };
  const atmoR = 1.13;
  atmoU.uEdge.value = Math.sqrt(1 - 1 / (atmoR * atmoR));
  const atmo = new THREE.Mesh(new THREE.SphereGeometry(atmoR, 64, 48), new THREE.ShaderMaterial({
    uniforms: atmoU, vertexShader: HERO_GLSL.fresV, fragmentShader: HERO_GLSL.atmoF,
    side: THREE.BackSide, transparent: true, depthWrite: false, blending: THREE.AdditiveBlending
  }));
  tilt.add(atmo);

  /* land dots */
  const tash = heroVec(HERO_TASH.lat, HERO_TASH.lon);
  const land = heroLandGeometry(mobile);
  const dotsU = {
    uTime, uSize: { value: 4 }, uReveal: { value: 0 }, uPingT: { value: -1 }, uD0: { value: 5 }, uHoverK: { value: 0 },
    uTash: { value: tash.clone() }, uPing: { value: tash.clone() }, uHover: { value: tash.clone() },
    uColA: { value: C('#2ee6d6') }, uColB: { value: C('#3d8bff') }, uGold: { value: C('#ffc861') }
  };
  if (land) {
    const dots = new THREE.Points(land.geo, new THREE.ShaderMaterial({
      uniforms: dotsU, vertexShader: HERO_GLSL.dotsV, fragmentShader: HERO_GLSL.dotsF,
      transparent: true, depthWrite: false, blending: THREE.AdditiveBlending
    }));
    spin.add(dots);
  }

  /* graticule + Ulugʻbek (Samarqand) meridian */
  const gp = [];
  const gv = (la, lo) => { const p = heroVec(la, lo, 1.0015); gp.push(p.x, p.y, p.z); };
  for (let la = -75; la <= 75; la += 15) for (let lo = -180; lo < 180; lo += 3) { gv(la, lo); gv(la, lo + 3); }
  for (let lo = -180; lo < 180; lo += 15) for (let la = -84; la < 84; la += 3) { gv(la, lo); gv(la + 3, lo); }
  const gGeo = new THREE.BufferGeometry();
  gGeo.setAttribute('position', new THREE.Float32BufferAttribute(gp, 3));
  const gratMat = new THREE.LineBasicMaterial({ color: C('#3d8bff'), transparent: true, opacity: 0, depthWrite: false, blending: THREE.AdditiveBlending });
  spin.add(new THREE.LineSegments(gGeo, gratMat));

  /* Ulugʻbek meridian: a graduated gold sextant arc through Samarqand (66°58′E), lat 22°→60° */
  const MER_LON = 66.97, MER_A = 22, MER_B = 60;
  const mp = [], ma = [];
  const mv = (la, lo, t) => { const p = heroVec(la, lo, 1.004); mp.push(p.x, p.y, p.z); ma.push(t); };
  for (let la = MER_A; la < MER_B; la += 0.5) { mv(la, MER_LON, (la - MER_A) / (MER_B - MER_A)); mv(la + 0.5, MER_LON, (la + 0.5 - MER_A) / (MER_B - MER_A)); }
  for (let la = MER_A + 2; la < MER_B; la += 2) {
    const t = (la - MER_A) / (MER_B - MER_A), w = la % 10 === 0 ? 1.5 : 0.7;
    mv(la, MER_LON - w, t); mv(la, MER_LON + w, t);
  }
  const mGeo = new THREE.BufferGeometry();
  mGeo.setAttribute('position', new THREE.Float32BufferAttribute(mp, 3));
  mGeo.setAttribute('aAng', new THREE.Float32BufferAttribute(ma, 1));
  const merMat = new THREE.ShaderMaterial({
    uniforms: { uDraw: { value: 0 }, uHead: { value: 0 }, uTrail: { value: 0.9 }, uAlpha: { value: 0.5 }, uEnds: { value: 1 }, uCol: { value: C('#ffc861') } },
    vertexShader: HERO_GLSL.lineV, fragmentShader: HERO_GLSL.lineF, transparent: true, depthWrite: false, blending: THREE.AdditiveBlending
  });
  spin.add(new THREE.LineSegments(mGeo, merMat));

  /* route arcs */
  const tubeR = mobile ? 0.0062 : 0.0042;
  const arcs = HERO_HUBS.map((h, i) => {
    const b = heroVec(h.lat, h.lon);
    const ang = tash.angleTo(b);
    const alt = (0.045 + ang * 0.25) * (h.m === 3 ? 1.5 : h.m === 2 ? 0.8 : 1);
    const sinA = Math.sin(ang);
    const pts = [];
    for (let s = 0; s <= 48; s++) {
      const t = s / 48;
      const p = new THREE.Vector3().addScaledVector(tash, Math.sin((1 - t) * ang) / sinA).addScaledVector(b, Math.sin(t * ang) / sinA);
      pts.push(p.multiplyScalar(1.002 + alt * Math.sin(Math.PI * t)));
    }
    const curve = new THREE.CatmullRomCurve3(pts);
    const u = {
      uTime, uDraw: { value: 0 }, uHi: { value: 0 }, uAlpha: { value: 1 }, uRev: { value: h.rev ? 1 : 0 },
      uSpeed: { value: MU.clamp(0.26 / (ang + 0.35), 0.14, 0.42) }, uOff: { value: (i * 0.137) % 1 },
      uCol: { value: C(HERO_MODE_HEX[h.m]) }
    };
    const mesh = new THREE.Mesh(new THREE.TubeGeometry(curve, 120, tubeR, 5, false), new THREE.ShaderMaterial({
      uniforms: u, vertexShader: HERO_GLSL.uvV, fragmentShader: HERO_GLSL.arcF,
      transparent: true, depthWrite: false, blending: THREE.AdditiveBlending
    }));
    spin.add(mesh);
    return { hub: h, curve, u, end: b, show: 0, hi: 0 };
  });

  /* sprites: pulse heads (12) + hub dots (12) + Toshkent core + satellite */
  const NS = arcs.length * 2 + 2;
  const sPos = new Float32Array(NS * 3), sCol = new Float32Array(NS * 3), sA = new Float32Array(NS), sSize = new Float32Array(NS);
  const setCol = (i, hex) => { const c = C(hex); sCol.set([c.r, c.g, c.b], i * 3); };
  arcs.forEach((a, i) => {
    setCol(i, HERO_MODE_HEX[a.hub.m]); sSize[i] = mobile ? 12 : 15;
    const j = arcs.length + i;
    setCol(j, HERO_MODE_HEX[a.hub.m]); sSize[j] = mobile ? 7 : 8;
    sPos.set(a.end.clone().multiplyScalar(1.004).toArray(), j * 3);
  });
  const TI = arcs.length * 2, SAT = TI + 1;
  setCol(TI, '#ffc861'); sSize[TI] = mobile ? 14 : 15; sPos.set(tash.clone().multiplyScalar(1.004).toArray(), TI * 3);
  setCol(SAT, '#7ff5ea'); sSize[SAT] = mobile ? 9 : 10;
  const sGeo = new THREE.BufferGeometry();
  sGeo.setAttribute('position', new THREE.BufferAttribute(sPos, 3).setUsage(THREE.DynamicDrawUsage));
  sGeo.setAttribute('aCol', new THREE.BufferAttribute(sCol, 3));
  sGeo.setAttribute('aA', new THREE.BufferAttribute(sA, 1).setUsage(THREE.DynamicDrawUsage));
  sGeo.setAttribute('aSize', new THREE.BufferAttribute(sSize, 1));
  const spriteU = { uPx: { value: dpr }, uD0: { value: 5 } };
  const sprites = new THREE.Points(sGeo, new THREE.ShaderMaterial({
    uniforms: spriteU, vertexShader: HERO_GLSL.spriteV, fragmentShader: HERO_GLSL.spriteF,
    transparent: true, depthWrite: false, blending: THREE.AdditiveBlending
  }));
  sprites.frustumCulled = false;
  spin.add(sprites);

  /* pulsing rings on the surface (hubs + big triple ring at Toshkent) */
  const zAxis = new THREE.Vector3(0, 0, 1), yAxis = new THREE.Vector3(0, 1, 0);
  const ringGeo = new THREE.PlaneGeometry(1, 1);
  const makeRing = (n, size, hex, count, off, speed) => {
    const u = { uTime, uOff: { value: off }, uShow: { value: 0 }, uCount: { value: count }, uSpeed: { value: speed }, uCol: { value: C(hex) } };
    const m = new THREE.Mesh(ringGeo, new THREE.ShaderMaterial({
      uniforms: u, vertexShader: HERO_GLSL.uvV, fragmentShader: HERO_GLSL.ringF,
      transparent: true, depthWrite: false, blending: THREE.AdditiveBlending, side: THREE.DoubleSide
    }));
    m.position.copy(n).multiplyScalar(1.005);
    m.quaternion.setFromUnitVectors(zAxis, n);
    m.scale.setScalar(size);
    spin.add(m);
    return u;
  };
  arcs.forEach((a, i) => { a.ring = makeRing(a.end, mobile ? 0.1 : 0.075, HERO_MODE_HEX[a.hub.m], 1, i * 0.23, 0.5); });
  const tashRing = makeRing(tash, 0.26, '#ffc861', 3, 0, 0.32);

  /* Toshkent light beam: thin core + soft halo */
  const beamU = [];
  [[0.003, 0.005, 1.1], [0.012, 0.024, 0.28]].forEach(([rt, rb, int]) => {
    const u = { uTime, uGrow: { value: 0 }, uInt: { value: int }, uCol: { value: C('#ffc861') } };
    const h = 0.34;
    const m = new THREE.Mesh(new THREE.CylinderGeometry(rt, rb, h, 16, 1, true), new THREE.ShaderMaterial({
      uniforms: u, vertexShader: HERO_GLSL.uvV, fragmentShader: HERO_GLSL.beamF,
      transparent: true, depthWrite: false, blending: THREE.AdditiveBlending, side: THREE.DoubleSide
    }));
    m.quaternion.setFromUnitVectors(yAxis, tash);
    m.position.copy(tash).multiplyScalar(1 + h / 2);
    spin.add(m);
    beamU.push(u);
  });

  /* astrolabe ring (gold, ticks) + satellite orbit (turquoise) */
  const lineMat = (hex, alpha, trail) => new THREE.ShaderMaterial({
    uniforms: { uDraw: { value: 0 }, uHead: { value: 0 }, uTrail: { value: trail }, uAlpha: { value: alpha }, uEnds: { value: 0 }, uCol: { value: C(hex) } },
    vertexShader: HERO_GLSL.lineV, fragmentShader: HERO_GLSL.lineF,
    transparent: true, depthWrite: false, blending: THREE.AdditiveBlending
  });
  const ringA = new THREE.Group(), ringB = new THREE.Group();
  const astroMat = lineMat('#ffc861', 0.3, 0.0);
  ringA.add(new THREE.LineSegments(heroRingGeometry(1.24, { ticks: 120, major: 10, tickLen: 0.016, majorLen: 0.042, inner: 1.225 }), astroMat));
  ringA.rotation.set(0.3, 0, -0.22);
  const orbitMat = lineMat('#2ee6d6', 0.22, 2.6);
  const orbit = new THREE.LineSegments(heroRingGeometry(1.42), orbitMat);
  ringB.add(orbit);
  ringB.rotation.set(1.18, 0, 0.62);
  tilt.add(ringA, ringB);
  const satLocal = new THREE.Vector3();

  /* composer (bloom on desktop) */
  let composer = null, bloom = null;
  if (bloomOn) {
    const rt = new THREE.WebGLRenderTarget(4, 4, { type: THREE.HalfFloatType, samples: dpr > 1.2 ? 2 : 4 });
    composer = new THREE.EffectComposer(renderer, rt);
    composer.setPixelRatio(dpr);
    composer.addPass(new THREE.RenderPass(scene, camera));
    bloom = new THREE.UnrealBloomPass(new THREE.Vector2(256, 256), 0.85, 0.5, 0.42);
    composer.addPass(bloom);
    composer.addPass(new THREE.OutputPass());
  }

  /* HTML labels projected from 3D */
  const mkLabel = (html, cls, color) => {
    const el = document.createElement('span');
    el.className = 'hero-lbl' + (cls ? ' ' + cls : '');
    el.innerHTML = html;
    if (color) el.style.setProperty('--lbl-c', color);
    labelsEl.appendChild(el);
    return el;
  };
  const labels = arcs.map(a => ({
    el: mkLabel(a.hub.n, '', HERO_MODE_VAR[a.hub.m]), local: a.end.clone().multiplyScalar(1.01), arc: a, left: false, o: -1, hot: false, hotV: 0
  }));
  labels.push({
    el: mkLabel('Toshkent<small>41.31°N · 69.24°E</small>', 'hero-lbl--tash'),
    local: tash.clone().multiplyScalar(1.36), tash: true, left: false, o: -1
  });

  /* ------------------------------------------------ state */
  const S = {
    dolly: 1, spinIntro: -1.5, tiltIntro: 0.45, atmo: 0, ring: 0, beam: 0, fade: 0, tashShow: 0,
    auto: 0, drag: 0, dragV: 0, tiltD: 0, px: 0, py: 0, tpx: 0, tpy: 0, scroll: 0, sc: 0, mode: 0
  };
  let W = 1, H = 1, Lc = { cx: 0, cy: 0, r: 100 }, D = 5, stacked = false, pingT = -1;

  function layout() {
    W = Math.max(1, stage.clientWidth); H = Math.max(1, stage.clientHeight);
    stacked = stackedMq.matches;
    const cs = getComputedStyle(root);
    const f = (n, d) => { const v = parseFloat(cs.getPropertyValue(n)); return isNaN(v) ? d : v; };
    const r = Math.min(f('--g-rh', 0.6) * H, f('--g-rw', 1) * W);
    Lc = { cx: f('--g-cx', 0.7) * W, cy: f('--g-cy', 0.5) * H, r };
    const tanHalf = Math.tan(camera.fov * HERO_DEG / 2);
    const alpha = Math.atan((r / (H / 2)) * tanHalf);
    D = 1 / Math.sin(alpha);
    camera.aspect = W / H;
    renderer.setSize(W, H, false);
    if (composer) composer.setSize(W, H);
    const spacing = r * (land ? land.step : 1) * HERO_DEG;       /* px between neighbouring dots at the equator */
    dotsU.uSize.value = spacing * 0.58 * dpr;
    dotsU.uD0.value = spriteU.uD0.value = D - 1;
    bgU.uAspect.value = W / H;
    bgU.uR.value = r / H;
    labels.forEach(l => { l.w = 0; });
  }

  function place(scrollS) {
    /* the globe sinks with scroll (in-scene parallax so the canvas never gets clipped) */
    const cy = Lc.cy + scrollS * H * (stacked ? 0.22 : 0.3);
    const cx = Lc.cx - (stacked ? 0 : scrollS * W * 0.06);
    camera.setViewOffset(W, H, W / 2 - cx, H / 2 - cy, W, H);
    bgU.uC.value.set(cx / W, 1 - cy / H);
  }

  /* ------------------------------------------------ mode highlight */
  function setMode(m) {
    S.mode = m;
    arcs.forEach(a => gsap.to(a.u.uHi, { value: a.hub.m === m ? 1 : 0, duration: 0.9, ease: 'power2.out', overwrite: true }));
    labels.forEach(l => {
      if (!l.arc) return;
      l.hot = l.arc.hub.m === m;
      l.el.classList.toggle('is-hot', l.hot);
      gsap.to(l, { hotV: l.hot ? 1 : 0, duration: l.hot ? 0.9 : 0.4, delay: l.hot ? 0.25 : 0, ease: 'power2.out', overwrite: true });
    });
  }

  /* ------------------------------------------------ interaction */
  const ray = new THREE.Raycaster();
  const sphere = new THREE.Sphere(new THREE.Vector3(), 1);
  const hit = new THREE.Vector3();
  const ndc = new THREE.Vector2();
  function pick(clientX, clientY, out) {
    const rect = canvas.getBoundingClientRect();
    ndc.set(((clientX - rect.left) / rect.width) * 2 - 1, -((clientY - rect.top) / rect.height) * 2 + 1);
    ray.setFromCamera(ndc, camera);
    if (!ray.ray.intersectSphere(sphere, hit)) return false;
    spin.worldToLocal(hit);
    out.copy(hit.normalize());
    return true;
  }
  function ping(clientX, clientY) {
    if (pick(clientX, clientY, dotsU.uPing.value)) pingT = 0;
  }
  /* pointer "flashlight": dots under the cursor light up and lift */
  const hover = { k: 0, t: 0, x: 0, y: 0, dirty: false };
  if (!MU.isTouch && !MU.reduced) {
    stage.addEventListener('pointermove', e => { hover.x = e.clientX; hover.y = e.clientY; hover.dirty = true; }, { passive: true });
    stage.addEventListener('pointerleave', () => { hover.t = 0; hover.dirty = false; });
  }

  const drag = { on: false, id: null, x: 0, y: 0, t: 0, moved: 0, sx: 0, sy: 0, last: -1e9 };
  stage.addEventListener('pointerdown', e => {
    if (e.button !== 0) return;
    Object.assign(drag, { on: true, id: e.pointerId, x: e.clientX, y: e.clientY, sx: e.clientX, sy: e.clientY, t: performance.now(), moved: 0 });
    if (!MU.isTouch) { try { stage.setPointerCapture(e.pointerId); } catch (err) { /* ignore */ } stage.classList.add('is-dragging'); S.dragV = 0; }
  });
  stage.addEventListener('pointermove', e => {
    if (!drag.on || e.pointerId !== drag.id) return;
    const dx = e.clientX - drag.x, dy = e.clientY - drag.y;
    drag.moved += Math.abs(dx) + Math.abs(dy);
    drag.x = e.clientX; drag.y = e.clientY;
    if (MU.isTouch) return;          /* touch keeps native vertical scroll; taps still ping */
    const now = performance.now(), dts = Math.max(8, now - drag.t) / 1000;
    drag.t = now;
    const k = 1.1 / Math.max(200, Lc.r);   /* ≈ the surface follows the pointer */
    S.drag += dx * k;
    S.dragV = MU.lerp(S.dragV, (dx * k) / dts, 0.5);
    drag.last = now;
    S.tiltD = MU.clamp(S.tiltD + dy * k * 1.1, -0.45, 0.45);
    if (drag.moved > 40) root.classList.add('is-dragged');
  });
  const endDrag = e => {
    if (!drag.on || (e && e.pointerId !== drag.id)) return;
    drag.on = false;
    stage.classList.remove('is-dragging');
    if (performance.now() - drag.t > 90) S.dragV *= 0.3;
    if (e && e.type === 'pointerup' && drag.moved < 8) ping(e.clientX, e.clientY);
  };
  stage.addEventListener('pointerup', endDrag);
  stage.addEventListener('pointercancel', endDrag);
  if (!MU.isTouch && !MU.reduced) {
    window.addEventListener('pointermove', e => {
      S.tpx = e.clientX / window.innerWidth - 0.5;
      S.tpy = e.clientY / window.innerHeight - 0.5;
    }, { passive: true });
  }

  /* ------------------------------------------------ per-frame */
  const tmp = new THREE.Vector3(), nrm = new THREE.Vector3(), toCam = new THREE.Vector3();
  function updateLabels() {
    const xMin = stacked ? -40 : W * 0.42, xFade = stacked ? 1 : W * 0.06;
    for (const l of labels) {
      tmp.copy(l.local).applyMatrix4(spin.matrixWorld);
      nrm.copy(tmp).normalize();
      toCam.copy(camera.position).sub(tmp).normalize();
      const facing = nrm.dot(toCam);
      tmp.project(camera);
      const x = (tmp.x + 1) * 0.5 * W, y = (1 - tmp.y) * 0.5 * H;
      let o;
      if (l.tash) o = S.tashShow * MU.clamp((facing + 0.1) / 0.3);
      else o = l.arc.show * MU.clamp((facing - 0.12) / 0.22) * l.hotV;
      o *= MU.clamp((x - xMin) / xFade);
      if (!l.w) l.w = l.el.offsetWidth + 34;
      const left = l.tash ? x + l.w > W - 8 : x < Lc.cx - 4;
      if ((left ? x - l.w < 4 : x + l.w > W - 4) || y < 10 || y > H - 10) o = 0;
      if (left !== l.left) {
        l.left = left;
        if (l.tash) l.el.classList.toggle('is-flip', left); else l.el.style.flexDirection = left ? 'row-reverse' : '';
      }
      if (Math.abs(o - l.o) > 0.004 || o > 0) {
        l.o = o;
        l.el.style.opacity = o.toFixed(3);
        if (o > 0) l.el.style.transform = `translate3d(${x.toFixed(1)}px,${y.toFixed(1)}px,0) translate(${left ? '-100%' : '0'},${l.tash ? '-100%' : '-50%'})`;
      }
    }
  }

  function frame(time, dt) {
    uTime.value = time;
    S.px = MU.damp(S.px, S.tpx, 2.2, dt);
    S.py = MU.damp(S.py, S.tpy, 2.2, dt);
    if (!drag.on) {
      S.drag += S.dragV * dt;
      S.dragV = MU.damp(S.dragV, 0, 1.5, dt);
      S.tiltD = MU.damp(S.tiltD, 0, 1.2, dt);
      /* after a while the globe glides home so Toshkent is always the focal point */
      if (performance.now() - drag.last > 3800 && Math.abs(S.dragV) < 0.08) {
        const home = Math.round(S.drag / (Math.PI * 2)) * Math.PI * 2;
        S.drag = MU.damp(S.drag, home, 0.9, dt);
      }
    }
    /* slow auto-rotation: an unhurried sway around Central Asia (period ≈ 100 s) */
    S.auto = Math.sin(time * 0.063) * 0.26 + Math.sin(time * 0.021) * 0.08;
    S.sc = MU.damp(S.sc, S.scroll, 6, dt);

    spin.rotation.y = HERO_BASE_SPIN + S.spinIntro + S.auto + S.drag + S.sc * 0.9;
    tilt.rotation.x = HERO_BASE_TILT + S.tiltIntro + S.tiltD + S.py * 0.1 + S.sc * 0.18;
    tilt.rotation.z = -S.px * 0.05;

    const dist = D * (1 + S.dolly * 1.7) * (1 - S.sc * 0.2);
    const ox = S.px * 0.2, oy = -S.py * 0.12;
    camera.position.set(Math.sin(ox) * Math.cos(oy) * dist, Math.sin(oy) * dist, Math.cos(ox) * Math.cos(oy) * dist);
    camera.lookAt(0, 0, 0);
    place(S.sc);

    if (hover.dirty) { hover.dirty = false; hover.t = pick(hover.x, hover.y, dotsU.uHover.value) ? 1 : 0; }
    hover.k = MU.damp(hover.k, hover.t * S.fade, 6, dt);
    dotsU.uHoverK.value = hover.k;
    if (pingT >= 0) { pingT += dt; dotsU.uPingT.value = pingT; if (pingT > 5) { pingT = -1; dotsU.uPingT.value = -1; } }

    /* uniforms from the intro state */
    bgU.uFade.value = 0.35 + 0.65 * S.fade;
    starU.uFade.value = S.fade;
    oceanU.uAtmo.value = S.atmo * gain;
    atmoU.uAtmo.value = S.atmo * gain;
    gratMat.opacity = 0.075 * S.atmo;
    merMat.uniforms.uDraw.value = S.ring;
    merMat.uniforms.uHead.value = (time * 0.12) % 1;
    astroMat.uniforms.uDraw.value = S.ring;
    orbitMat.uniforms.uDraw.value = S.ring;
    beamU.forEach(u => { u.uGrow.value = S.beam; });
    tashRing.uShow.value = S.beam;

    /* rings + satellite */
    ringA.rotation.y = time * 0.02;
    const satA = (time * 0.055) % 1;
    orbitMat.uniforms.uHead.value = satA;
    satLocal.set(Math.cos(satA * Math.PI * 2) * 1.42, 0, Math.sin(satA * Math.PI * 2) * 1.42);
    ringB.localToWorld(satLocal); spin.worldToLocal(satLocal);
    sPos.set([satLocal.x, satLocal.y, satLocal.z], SAT * 3);
    sA[SAT] = S.ring * 0.7;

    /* pulse heads follow the shader's head position */
    arcs.forEach((a, i) => {
      const head = (time * a.u.uSpeed.value + a.u.uOff.value) % 1;
      const p = a.curve.getPointAt(a.hub.rev ? 1 - head : head, tmp);
      sPos.set([p.x, p.y, p.z], i * 3);
      const edge = Math.min(1, head * 12, (1 - head) * 12);
      sA[i] = a.show * edge * (0.45 + 0.55 * a.u.uHi.value);
      sA[arcs.length + i] = a.show;
      a.ring.uShow.value = a.show * (0.55 + 0.45 * a.u.uHi.value);
    });
    sA[TI] = S.beam;
    sGeo.attributes.position.needsUpdate = true;
    sGeo.attributes.aA.needsUpdate = true;

    if (composer) composer.render(dt); else renderer.render(scene, camera);
    updateLabels();
  }

  /* ------------------------------------------------ lifecycle */
  layout(); place(0);
  let loop = null;
  if (MU.reduced) finalStateNow();
  const renderOnce = () => frame(gsap.ticker.time, 0);
  if (!MU.reduced) {
    loop = MU.renderLoop(root, frame);
    loop.stop();          /* started on reveal; compile now so the first frame is not a hitch */
    try { renderer.compile(scene, camera); } catch (e) { /* ignore */ }
  }
  const ro = new ResizeObserver(() => { layout(); if (!loop || !loop.running) renderOnce(); });
  ro.observe(stage);

  function finalStateNow() { finalState(); }
  function finalState() {
    Object.assign(S, { dolly: 0, spinIntro: 0, tiltIntro: 0, atmo: 1, ring: 1, beam: 1, fade: 1, tashShow: 1 });
    dotsU.uReveal.value = 1;
    arcs.forEach(a => { a.u.uDraw.value = 1; a.show = 1; });
    labels.forEach(l => { if (l.arc) l.hotV = l.hot ? 1 : 0; });
    gsap.set(canvas, { opacity: 1 });
  }

  function intro() {
    if (MU.reduced) { finalState(); setMode(S.mode); renderOnce(); return null; }
    loop.start();
    const tl = gsap.timeline();
    tl.to(canvas, { opacity: 1, duration: 1.2, ease: 'power1.out' }, 0)
      .to(S, { fade: 1, duration: 2.2, ease: 'power2.out' }, 0)
      .to(S, { dolly: 0, duration: 3.1, ease: 'expo.out' }, 0)
      .to(S, { spinIntro: 0, duration: 3.6, ease: 'power4.out' }, 0)
      .to(S, { tiltIntro: 0, duration: 3.2, ease: 'power3.out' }, 0)
      .to(dotsU.uReveal, { value: 1, duration: 2.8, ease: 'power2.inOut' }, 0.15)
      .to(S, { atmo: 1, duration: 2.4, ease: 'power2.out' }, 0.35)
      .to(S, { ring: 1, duration: 2.6, ease: 'power3.inOut' }, 0.7)
      .to(S, { beam: 1, duration: 1.3, ease: 'power3.out' }, 0.9)
      .to(S, { tashShow: 1, duration: 0.9, ease: 'power2.out' }, 1.5);
    arcs.forEach((a, i) => {
      const t0 = 1.15 + i * 0.12;
      tl.to(a.u.uDraw, { value: 1, duration: 1.25, ease: 'power2.inOut' }, t0)
        .to(a, { show: 1, duration: 0.8, ease: 'power2.out' }, t0 + 1.0);
    });
    return tl;
  }

  return {
    setMode, intro, finalState,
    get stacked() { return stacked; },
    setScroll(p) { if (!MU.reduced) S.scroll = p; },   /* reduced motion: the globe stays put */
    renderOnce
  };
}

/* ================================================================== overlay helpers */
function heroSlot(root, MU, onMode) {
  const { gsap } = MU;
  const words = Array.from(root.querySelectorAll('.hero-slot__word'));
  const modes = root.querySelector('[data-hero-modes]');
  const btns = modes ? Array.from(modes.querySelectorAll('.hero-modes__item')) : [];
  const pill = modes && modes.querySelector('.hero-modes__pill');
  let cur = 0, call = null, visible = true, started = false;

  const placePill = (i, instant) => {
    const b = btns[i];
    if (!b || !pill) return;
    modes.style.setProperty('--pill', HERO_MODE_VAR[i]);
    const vars = { x: b.offsetLeft, width: b.offsetWidth };
    if (instant || MU.reduced) gsap.set(pill, vars); else gsap.to(pill, Object.assign(vars, { duration: 0.7, ease: 'expo.out', overwrite: true }));
    btns.forEach((x, k) => { x.classList.toggle('is-on', k === i); x.setAttribute('aria-pressed', k === i ? 'true' : 'false'); });
  };

  gsap.set(words.slice(1), { yPercent: 110, autoAlpha: 0 });
  if (!MU.reduced) gsap.set(words[0], { yPercent: 110 });

  function show(i) {
    if (i === cur) return;
    const out = words[cur], inn = words[i];
    cur = i;
    if (MU.reduced) {
      gsap.set(out, { autoAlpha: 0 }); gsap.set(inn, { yPercent: 0, autoAlpha: 1 });
    } else {
      gsap.to(out, { yPercent: -110, skewY: -7, autoAlpha: 0, duration: 0.6, ease: 'power3.in', overwrite: true });
      gsap.fromTo(inn, { yPercent: 110, skewY: 7, autoAlpha: 1 }, { yPercent: 0, skewY: 0, duration: 1.05, ease: 'expo.out', delay: 0.22, overwrite: true, clearProps: 'transform' });
    }
    placePill(i);
    onMode(i);
  }
  const schedule = d => {
    if (call) call.kill();
    call = null;
    if (!visible || !started || MU.reduced) return;
    call = gsap.delayedCall(d, () => { show((cur + 1) % words.length); schedule(3.2); });
  };
  btns.forEach((b, i) => b.addEventListener('click', () => { show(i); schedule(7); }));

  return {
    intro() {
      placePill(0, true);
      onMode(0);
      if (!MU.reduced) gsap.to(words[0], { yPercent: 0, duration: 1.3, ease: 'expo.out', delay: 0.72, clearProps: 'transform' });
      started = true;
      schedule(4.2);
    },
    setVisible(v) { if (v === visible) return; visible = v; schedule(2.4); },
    relayout() { placePill(cur, true); }
  };
}

function heroTimers(root) {
  const clock = root.querySelector('[data-hero-clock]');
  const eta = root.querySelector('[data-hero-eta]');
  const pad = n => String(n).padStart(2, '0');
  let left = 3 * 86400 + 14 * 3600 + 22 * 60 + 9;   /* seconds until the demo train reaches Toshkent */
  let timer = null;
  const renderClock = () => {
    const d = new Date(Date.now() + 5 * 3600 * 1000);
    if (clock) clock.textContent = `${pad(d.getUTCHours())}:${pad(d.getUTCMinutes())}:${pad(d.getUTCSeconds())}`;
  };
  const renderEta = animate => {
    if (!eta) return;
    const d = Math.floor(left / 86400), h = Math.floor((left % 86400) / 3600), m = Math.floor((left % 3600) / 60), s = left % 60;
    eta.innerHTML = `${d} kun ${pad(h)}:${pad(m)}:<span class="hero-sec">${pad(s)}</span>`;
    if (animate && !MU.reduced) gsap.fromTo(eta.lastChild, { yPercent: -70, autoAlpha: 0 }, { yPercent: 0, autoAlpha: 1, duration: 0.45, ease: 'power3.out' });
  };
  const tick = () => { left = Math.max(0, left - 1); renderClock(); renderEta(true); };
  renderClock(); renderEta(false);
  return {
    run(on) {
      if (on && !timer) { renderClock(); timer = setInterval(tick, 1000); }
      else if (!on && timer) { clearInterval(timer); timer = null; }
    }
  };
}

/* ================================================================== part */
let heroApi = null;
MU.part('hero', {
  init(root, MU) {
    const { gsap } = MU;
    const copy = root.querySelector('.hero-copy');
    const cardWrap = root.querySelector('.hero-card-wrap');
    const hud = root.querySelector('.hero-rail');
    const hudRows = hud ? Array.from(hud.querySelectorAll('.hero-rail__in > *')) : [];
    const cue = root.querySelector('.hero-cue');
    const fill = root.querySelector('.hero-card__fill');
    const pathFg = root.querySelector('.hero-card__path-fg');
    const pct = root.querySelector('[data-hero-pct]');

    /* lock each stat to its final width before the count-up renders "0" */
    root.querySelectorAll('.hero-stat__v').forEach(el => { el.style.minWidth = Math.ceil(el.getBoundingClientRect().width) + 'px'; });

    const globe = heroGlobe(root, MU);
    const slot = heroSlot(root, MU, m => { if (globe) globe.setMode(m); });
    const timers = heroTimers(root);

    /* initial (pre-reveal) states for the hand-made choreography */
    if (!MU.reduced) {
      gsap.set(hudRows, { autoAlpha: 0, y: -30 });
      gsap.set(fill, { width: '0%' });
      if (pathFg) gsap.set(pathFg, { strokeDashoffset: 100 });
      if (pct) pct.textContent = '0';
    } else {
      gsap.set(cue, { opacity: 1 });
      if (pathFg) gsap.set(pathFg, { strokeDashoffset: 32 });
    }

    /* pause loops offscreen */
    MU.onVisible(root, vis => {
      root.classList.toggle('is-inview', vis);
      timers.run(vis);
      slot.setVisible(vis);
    }, '0px');

    /* scroll choreography */
    MU.mm.add({
      wide: '(min-width: 901px) and (orientation: landscape), (min-width: 1101px)',
      narrow: '(max-width: 900px), (orientation: portrait) and (max-width: 1100px)'
    }, ctx => {
      const { wide } = ctx.conditions;
      const blur = { v: 0 };
      const setBlur = () => { copy.style.filter = blur.v > 0.02 ? `blur(${(blur.v * 12).toFixed(2)}px)` : ''; };
      const tl = gsap.timeline({
        defaults: { ease: 'none' },
        scrollTrigger: {
          trigger: root, start: 'top top', end: 'bottom top', scrub: wide ? 0.6 : true, invalidateOnRefresh: true,
          onUpdate: s => { if (globe) globe.setScroll(s.progress); }
        }
      });
      if (!MU.reduced) {
        if (wide) {
          tl.fromTo(copy, { y: 0, autoAlpha: 1 }, { y: () => -window.innerHeight * 0.22, autoAlpha: 0, ease: 'power1.in', duration: 0.62 }, 0)
            .fromTo(blur, { v: 0 }, { v: 1, ease: 'power2.in', duration: 0.62, onUpdate: setBlur }, 0)
            .fromTo(cardWrap, { y: 0, autoAlpha: 1 }, { y: () => -window.innerHeight * 0.34, autoAlpha: 0, ease: 'power1.in', duration: 0.55 }, 0)
            .fromTo(hud, { autoAlpha: 1 }, { autoAlpha: 0, duration: 0.3 }, 0)
            .fromTo(cue, { y: 0 }, { y: 40, duration: 0.25 }, 0);
        } else {
          tl.fromTo(hud, { autoAlpha: 1 }, { autoAlpha: 0, duration: 0.15 }, 0);
        }
      }
      tl.set({}, {}, 1);
      return () => { copy.style.filter = ''; };
    });

    heroApi = {
      reveal() {
        if (globe) globe.intro();
        slot.intro();
        if (MU.reduced) return;
        gsap.to(hudRows, { autoAlpha: 1, y: 0, duration: 1.2, stagger: 0.1, ease: 'expo.out', delay: 1.6 });
        gsap.to(cue, { opacity: 1, duration: 1, delay: 2.6 });
        const o = { v: 0 };
        gsap.timeline({ delay: 2.1 })
          .to(fill, { width: '68%', duration: 2.2, ease: 'power3.inOut' }, 0)
          .to(pathFg, { strokeDashoffset: 32, duration: 2.2, ease: 'power3.inOut' }, 0)
          .to(o, { v: 68, duration: 2.2, ease: 'power3.inOut', onUpdate: () => { if (pct) pct.textContent = Math.round(o.v); } }, 0);
      },
      relayout: () => slot.relayout()
    };
    window.addEventListener('resize', () => {
      if (heroApi) heroApi.relayout();
      root.querySelectorAll('.hero-stat__v').forEach(el => { el.style.minWidth = ''; });
    }, { passive: true });
  },
  reveal() { if (heroApi) heroApi.reveal(); }
});
