#!/usr/bin/env node
/* Build-time generator for the hero globe land dots.
   node src/parts/10-hero/gen-land.mjs  ->  src/parts/10-hero/a-land.js
   Grid: rows every STEP degrees of latitude; each row has round(360*cos(lat)/STEP) evenly spaced
   longitudes (equal-area-ish spacing). A bitset over that deterministic grid marks land cells
   (geoContains on world-atlas land-110m) and a second bitset, indexed over the land dots only,
   marks Uzbekistan (countries-110m id 860). Runtime decodes the same grid. */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { feature } from 'topojson-client';
import { geoContains } from 'd3-geo';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const NM = path.resolve(HERE, '../../../node_modules');
const STEP = 0.9;

const landTopo = JSON.parse(fs.readFileSync(path.join(NM, 'world-atlas/land-110m.json'), 'utf8'));
const land = feature(landTopo, landTopo.objects.land);
const cTopo = JSON.parse(fs.readFileSync(path.join(NM, 'world-atlas/countries-110m.json'), 'utf8'));
const countries = feature(cTopo, cTopo.objects.countries);
const uz = countries.features.find(f => +f.id === 860);
if (!uz) throw new Error('Uzbekistan not found');

const rows = Math.round(180 / STEP);
const bits = [], uzBits = [];
let total = 0, nLand = 0, nUz = 0;
for (let i = 0; i < rows; i++) {
  const lat = -90 + (i + 0.5) * STEP;
  const n = Math.max(1, Math.round((360 * Math.cos(lat * Math.PI / 180)) / STEP));
  for (let j = 0; j < n; j++) {
    const lon = -180 + (j + 0.5) * (360 / n);
    const on = geoContains(land, [lon, lat]);
    bits.push(on ? 1 : 0);
    total++;
    if (on) {
      nLand++;
      const u = geoContains(uz, [lon, lat]) ? 1 : 0;
      uzBits.push(u); nUz += u;
    }
  }
}
const pack = arr => {
  const bytes = new Uint8Array(Math.ceil(arr.length / 8));
  arr.forEach((b, k) => { if (b) bytes[k >> 3] |= 1 << (k & 7); });
  return Buffer.from(bytes).toString('base64');
};
const out = `/* generated by gen-land.mjs — world-atlas land-110m, ${nLand} land dots of ${total} grid cells, step ${STEP}° */\n` +
  `window.muHeroLand = { step: ${STEP}, count: ${nLand}, land: "${pack(bits)}", uz: "${pack(uzBits)}" };\n`;
fs.writeFileSync(path.join(HERE, 'a-land.js'), out);
console.log(`land dots ${nLand} / ${total} cells · uzbekistan ${nUz} · ${(out.length / 1024).toFixed(1)} KB`);
